/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();
  static const String PLUGIN_NAME = 'app';
  static const String PLUGIN_VERSION = '1.0.3+4';
  static const String FENCE = 'assets/icons/fence.png';
  static const String GROUP = 'assets/icons/group.png';
  static const String MAP_END_POINT = 'assets/icons/map-end-point.png';
  static const String TEXT = 'assets/icons/text.png';
  static const String DOUBLE_RIGHT_ARROW = 'assets/images/double-right-arrow.png';
  static const String ERROR_INACTIVE = 'assets/images/error-inactive.png';
  static const String MAP_START_POINT = 'assets/images/map-start-point.png';
  static const String POINT_INACTIVE = 'assets/images/point-inactive.png';
  static const String USER = 'assets/images/user.png';
}
