/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
ImagesRes._();
  static const String PLUGIN_NAME = 'gpspro';
  static const String PLUGIN_VERSION = '1.0.3+4';
  static const String APPLE_STORE = 'images/apple-store.png';
  static const String ARROW_LEFT = 'images/arrow_left.gif';
  static const String ARROW_RIGHT = 'images/arrow_right.gif';
  static const String GOOGLE_PLAY = 'images/google-play.png';
  static const String GOOGLE_LOGO = 'images/google_logo.svg';
  static const String HISTORY2 = 'images/history2.png';
  static const String MARKER_ICON_2X = 'images/marker-icon-2x.png';
  static const String MARKER_ICON = 'images/marker-icon.png';
  static const String MARKER_SHADOW = 'images/marker-shadow.png';
  static const String NO_DATA_O = 'images/no-data-o.png';
  static const String NO_DATA = 'images/no-data.png';
  static const String NO_IMAGE = 'images/no-image.jpg';
  static const String NO_STREETVIEW_290X125 = 'images/no-streetview-290x125.jpg';
  static const String NO_STREETVIEW_598X313 = 'images/no-streetview-598x313.jpg';
  static const String NO_STREETVIEW = 'images/no-streetview.jpg';
  static const String REPORT_BARS = 'images/report_bars.jpg';
  static const String REPORT_CURVE = 'images/report_curve.jpg';
  static const String ROUTE_DRIVE = 'images/route_drive.png';
  static const String ROUTE_END = 'images/route_end.png';
  static const String ROUTE_EVENT = 'images/route_event.png';
  static const String ROUTE_START = 'images/route_start.png';
  static const String ROUTE_STOP = 'images/route_stop.png';
  static const String ZOOM_IN = 'images/zoom_in.png';
  static const String ZOOM_OUT = 'images/zoom_out.png';
}
