// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3cvpRL5YORZA0gabBJrOm_xi3khPl3oM',
    appId: '1:270985006580:web:63768140d43f8c5cfbfda1',
    messagingSenderId: '270985006580',
    projectId: 'smartlock-gps',
    authDomain: 'smartlock-gps.firebaseapp.com',
    storageBucket: 'smartlock-gps.firebasestorage.app',
    measurementId: 'G-35P6YPDJ7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9t_s6HR8kgdWPJd-AFSB-gA0OOw7tO1M',
    appId: '1:270985006580:android:95a63cc6b9cca4cafbfda1',
    messagingSenderId: '270985006580',
    projectId: 'smartlock-gps',
    storageBucket: 'smartlock-gps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEb8rUGehsqPe-Eag6Uaf3oKSsI7pdgQ8',
    appId: '1:270985006580:ios:47867ceb0392ac8bfbfda1',
    messagingSenderId: '270985006580',
    projectId: 'smartlock-gps',
    storageBucket: 'smartlock-gps.firebasestorage.app',
    iosBundleId: 'com.example.smartLock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEb8rUGehsqPe-Eag6Uaf3oKSsI7pdgQ8',
    appId: '1:270985006580:ios:47867ceb0392ac8bfbfda1',
    messagingSenderId: '270985006580',
    projectId: 'smartlock-gps',
    storageBucket: 'smartlock-gps.firebasestorage.app',
    iosBundleId: 'com.example.smartLock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3cvpRL5YORZA0gabBJrOm_xi3khPl3oM',
    appId: '1:270985006580:web:541eb9a705b2f660fbfda1',
    messagingSenderId: '270985006580',
    projectId: 'smartlock-gps',
    authDomain: 'smartlock-gps.firebaseapp.com',
    storageBucket: 'smartlock-gps.firebasestorage.app',
    measurementId: 'G-PJM7JW5JJH',
  );
}
